#!/usr/bin/env python
import rospy
import gi
import sys
import os
gi.require_version('Gst', '1.0')
from gi.repository import GObject, Gst
from speech_recognition.hmi_server_kaldi_client import HMIServerKaldiClient

if __name__ == "__main__":
    # Todo: Move below line somewhere else
    os.environ['GST_PLUGIN_PATH'] = "/home/amigo/src/kaldi_speech/src/gst-plugin/"

    # Initialize gstreamer library using threads
    GObject.threads_init()
    Gst.init(sys.argv)

    # rospy.set_param("/kaldi_model_path", "/home/amigo/ros/kinetic/repos/https_/github.com/tue-robotics/"
    #                                      "speech_recognition.git/gstreamer_live_spr/online-data/models/tri2b_mmi/")

    rospy.init_node('hmi_server_kaldi_client')
    c = HMIServerKaldiClient()

    # # Generate some required parameters.
    # description = ""
    # grammar = ""
    # target = ""
    # is_preempt_requested = False
    #
    # # Run the _determine_answer function once to recognize a command (single sentence/request)
    # c._determine_answer(description, grammar, target, is_preempt_requested)
    #
    # print("Finished.")

    rospy.spin()
